### ISSUE TITLE
When the code will be available?

### ISSUE THREAD

**Issue by tonysy** [czhang0528/MosaicOS#1]
Hi,
Thanks for the great work, I would like to know when the code will be available

**Comment by tydpan** [comment]
@tonysy Thanks for your interest. We just uploaded the script to synthesize mosaic images and annotations. You then can use the outputs to go through the training pipeline mentioned in our paper!

**Comment by jimmyflycv** [comment]
> @tonysy Thanks for your interest. We just uploaded the script to synthesize mosaic images and annotations. You then can use the outputs to go through the training pipeline mentioned in our paper!

hello，will u upload yolov4 mosaic script for compare work?

**Comment by czhang0528** [comment]
@jimmyflycv Thanks for your interest. We are not planning to release scripts for other comparable methods in this repo.
